### ISSUE TITLE
KeyError: 'RedditUser'

### ISSUE THREAD

**Issue by KauzDs** [dqdang/digested-clips#4]
I've complete all previous steps. When I run python 3 main.py I get the following error

`root@machine2:/home/USERNAME/Clips# python3 main.py 
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    R_USERNAME = os.environ['RedditUser']
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RedditUser'
root@machine2:/home/USERNAME/Clips#
`

Python 3.8
Ubuntu 20.4 LTS

**Comment by dqdang** [comment]
This is your Reddit username for the bot.
Pass in a hard value for that line like you did for the other values.
R_USERNAME = "YOUR_USERNAME"

**Comment by KauzDs** [comment]
I guess I should've made it clearer but that's exactly what I did. I filled `R_USERNAME = os.environ['RedditUser']` with the bots /u/botusarname, I just changed it to RedditUser on the snipped posted in the first message for privacy reasons.

Even the the correct reddit username I get that error

**Comment by dqdang** [comment]
KeyError comes up when the string is in the brackets of ``os.environ``. If you modified the code and left in ``R_USERNAME = os.environ['RedditUser']`` somewhere, just comment it out and replace it with something like this:

``R_USERNAME = "botusarname"``

Note that ``os.environ`` is not present in that line.

**Comment by KauzDs** [comment]
I'm terrible sorry for bugging you so much but I really want to make this work. I got everything working fine now except the upload step. 
How do I correctly set up the Youtube Data API and oauth2 parts, filled the client_secrets.json correctly etc but both youtube accounts I tried it on got terminated a few hours later (yesterday) https://i.imgur.com/6JuR5K4.png

What am I doing wrong?

**Comment by dqdang** [comment]
Hey no problem, I want this to work for you too :)

You may have to create another account since the current one is suspended :(

This is what my API page looks like:
![image](https://user-images.githubusercontent.com/10083357/86057389-f4a7bd00-ba13-11ea-992c-4471fe2d29ad.png)

1) To get to the screenshot window, **click the dropdown button** on the left of the page next to GoogleAPIs. There you can **create a new project**.
2) After creating the new project, make sure to **select** it in **the dropdown box** again and there should be a button that says "ENABLE APIs AND SERVICES". Click it and enter in the search box "youtube data". Select the one that says **YouTube Data API V3** and click **Enable**. Wait a bit for it to enable. This will allow your application to use the YouTube Data API.
3) Click **GoogleAPIs** to go back to the home application screen and click **Credentials**. Select **Create OAuth client ID**.
4) You may need to set a product name. Just click the configure button and click "External" (Can't do Internal unless you're a G Suite user).  Give your bot a name and click save at the bottom. Click **Credentials ** and select **Create OAuth client ID** again.
5) Select **Web application** and choose a name (this can be anything).
6) Afterwards, you have your G_CID and G_SECRET. :) Use these values in your ``client_secrets.json`` file.

If these steps are helpful, do you think I should add this to the README?

**Comment by KauzDs** [comment]
> If these steps are helpful, do you think I should add this to the README?
Yes, I was pretty lost without it lol


Ok, I used the web template for client_secrets.json, added ID and secret etc but now I'm having a different problem.


`python3 main.py
http://clips.twitch.tv/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Downloading clip slug: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

"clip name.." -> clip_name.mp4
https://clips-media-assets2.twitch.tv/xxxxxxxxxxxxxx.mp4
...100%
Done.


Traceback (most recent call last):
  File "main.py", line 71, in <module>
    youtube_mirror = uploader.upload(
  File "/home/ziralt0/Clips/uploader.py", line 212, in upload
    youtube = get_authenticated_service(args)
  File "/home/ziralt0/Clips/uploader.py", line 92, in get_authenticated_service
    credentials = run_flow(flow, storage, args)
  File "/usr/local/lib/python3.8/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/oauth2client/tools.py", line 195, in run_flow
    logging.getLogger().setLevel(getattr(logging, flags.logging_level))
AttributeError: 'dict' object has no attribute 'logging_level'
`

**Comment by dqdang** [comment]
Does a ``main.py-oauth2.json`` get created?

**Comment by KauzDs** [comment]
No it doesn't.

```
/usr/local/lib/python3.8/dist-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access main.py-oauth2.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
```

**Comment by dqdang** [comment]
How about an `uploader.py-oauth2.json`? If not, then the `client_secrets.json` isn't in the right directory or something might be missing from the secrets file.

Should look something like this:
![image](https://user-images.githubusercontent.com/10083357/86068624-c1bdf300-ba2c-11ea-9ee7-e6f67672abde.png)

**Comment by dqdang** [comment]
Does your ``client_secrets.json`` file look like this?:
![image](https://user-images.githubusercontent.com/10083357/86068803-18c3c800-ba2d-11ea-9db9-d315c4a71728.png)

**Comment by KauzDs** [comment]
> Does your client_secrets.json file look like this?

Yes, here's the client_secrets.json  [https://i.imgur.com/oLJtN80.png](https://i.imgur.com/oLJtN80.png)
and here's my files currently [https://i.imgur.com/vysBZJi.png](https://i.imgur.com/vysBZJi.png)

**Comment by dqdang** [comment]
Just fixed it. Try pulling the latest commit. You have to input all the authentication stuff again for the hardcoded stuff. Hoped you saved it somewhere.

**Comment by KauzDs** [comment]
pulled latest commit, filled everything again and now I get a new error

```
user@host:~/clips/digested-clips$ sudo python3 main.py
http://clips.twitch.tv/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Downloading clip slug: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
"clip_name.." -> clip_name.mp4
https://clips-media-assets2.twitch.tv/xxxxxxxxxxxx.mp4
...100%

Traceback (most recent call last):
  File "main.py", line 78, in <module>
    out = subprocess.Popen(cmd,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
```

**Comment by dqdang** [comment]
Try making an alias and put it in a .bashrc.

In terminal, open up a text editor and make a .bashrc file in your home directory. Then add the following line to it.

alias python=“sudo python3”

Then do :
$ source .bashrc

**Comment by KauzDs** [comment]
Same error still

**Comment by dqdang** [comment]
Made a commit, try pulling again and then see if it works.
